HC/Controllers/CCGsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HC.Models;

namespace HC.Controllers
{
    public class CCGsController : Controller
    {
        private HCContext db = new HCContext();

        // GET: /CCGs/
        public async Task<ActionResult> Index()
        {
            Session.Remove("CCGID");
            int? id = Convert.ToInt32(Session["HistoriaClinicaID"]);

            var ccgs = db.CCGs.Include(c => c.HistoriasClinicas).Where(h => h.HistoriaClinicaID == id);
            return View(await ccgs.ToListAsync());
        }

        // GET: /CCGs/Details/5
        public async Task<ActionResult> Details()
        {
            int? id = Convert.ToInt32(Session["CCGID"]);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CCGs ccgs = await db.CCGs.FindAsync(id);
            if (ccgs == null)
            {
                return HttpNotFound();
            }
            return View(ccgs);
        }

        // GET: /CCGs/Create
        public ActionResult Create()
        {
            ViewBag.HistoriaClinicaID = Session["HistoriaClinicaID"];
            return View();
        }

        // POST: /CCGs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include="CCGID,HistoriaClinicaID,Fecha,Tci,Da,Cx,Cd,Conclusion")] CCGs ccgs)
        {
            if (ModelState.IsValid)
            {
                db.CCGs.Add(ccgs);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.HistoriaClinicaID = new SelectList(db.HistoriasClinicas, "HistoriaClinicaID", "FactoresRiesgo", ccgs.HistoriaClinicaID);
            return View(ccgs);
        }

        // GET: /CCGs/Edit/5
        public async Task<ActionResult> Edit()
        {
            int? id = Convert.ToInt32(Session["CCGID"]);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CCGs ccgs = await db.CCGs.FindAsync(id);
            if (ccgs == null)
            {
                return HttpNotFound();
            }
            ViewBag.HistoriaClinicaID = Session["HistoriaClinicaID"];
            return View(ccgs);
        }

        // POST: /CCGs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include="CCGID,HistoriaClinicaID,Fecha,Tci,Da,Cx,Cd,Conclusion")] CCGs ccgs)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ccgs).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.HistoriaClinicaID = new SelectList(db.HistoriasClinicas, "HistoriaClinicaID", "FactoresRiesgo", ccgs.HistoriaClinicaID);
            return View(ccgs);
        }

        // GET: /CCGs/Delete/5
        public async Task<ActionResult> Delete()
        {
            int? id = Convert.ToInt32(Session["CCGID"]);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CCGs ccgs = await db.CCGs.FindAsync(id);
            if (ccgs == null)
            {
                return HttpNotFound();
            }
            return View(ccgs);
        }

        // POST: /CCGs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            CCGs ccgs = await db.CCGs.FindAsync(id);
            db.CCGs.Remove(ccgs);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult SetCCGID(int id, char op)
        {
            Session["CCGID"] = id;

            switch (op)
            {
                case 'B':
                    return RedirectToAction("Delete");
                case 'D':
                    return RedirectToAction("Details");
                case 'E':
                    return RedirectToAction("Edit");
                default:
                    return RedirectToAction("Index");
            }
        }
    }
}

HC/Controllers/ECOsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HC.Models;

namespace HC.Controllers
{
    public class ECOsController : Controller
    {
        private HCContext db = new HCContext();

        // GET: /ECOs/
        public async Task<ActionResult> Index()
        {
            Session.Remove("ECOID");
            int? id = Convert.ToInt32(Session["HistoriaClinicaID"]);

            var ecos = db.ECOs.Include(e => e.HistoriasClinicas).Where(h => h.HistoriaClinicaID == id);
            return View(await ecos.ToListAsync());
        }

        // GET: /ECOs/Details/5
        public async Task<ActionResult> Details()
        {
            int? id = Convert.ToInt32(Session["ECOID"]);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ECOs ecos = await db.ECOs.FindAsync(id);
            if (ecos == null)
            {
                return HttpNotFound();
            }
            return View(ecos);
        }

        // GET: /ECOs/Create
        public ActionResult Create()
        {
            ViewBag.HistoriaClinicaID = Session["HistoriaClinicaID"];
            return View();
        }

        // POST: /ECOs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include="ECOID,HistoriaClinicaID,Fecha,Vi,S,PP,Ao,Ai,Fey,Conclusion")] ECOs ecos)
        {
            if (ModelState.IsValid)
            {
                db.ECOs.Add(ecos);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.HistoriaClinicaID = new SelectList(db.HistoriasClinicas, "HistoriaClinicaID", "FactoresRiesgo", ecos.HistoriaClinicaID);
            return View(ecos);
        }

        // GET: /ECOs/Edit/5
        public async Task<ActionResult> Edit()
        {
            int? id = Convert.ToInt32(Session["ECOID"]);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ECOs ecos = await db.ECOs.FindAsync(id);
            if (ecos == null)
            {
                return HttpNotFound();
            }
            ViewBag.HistoriaClinicaID = Session["HistoriaClinicaID"];
            return View(ecos);
        }

        // POST: /ECOs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include="ECOID,HistoriaClinicaID,Fecha,Vi,S,PP,Ao,Ai,Fey,Conclusion")] ECOs ecos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ecos).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.HistoriaClinicaID = new SelectList(db.HistoriasClinicas, "HistoriaClinicaID", "FactoresRiesgo", ecos.HistoriaClinicaID);
            return View(ecos);
        }

        // GET: /ECOs/Delete/5
        public async Task<ActionResult> Delete()
        {
            int? id = Convert.ToInt32(Session["ECOID"]);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ECOs ecos = await db.ECOs.FindAsync(id);
            if (ecos == null)
            {
                return HttpNotFound();
            }
            return View(ecos);
        }

        // POST: /ECOs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            ECOs ecos = await db.ECOs.FindAsync(id);
            db.ECOs.Remove(ecos);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult SetECOID(int id, char op)
        {
            Session["ECOID"] = id;

            switch (op)
            {
                case 'B':
                    return RedirectToAction("Delete");
                case 'D':
                    return RedirectToAction("Details");
                case 'E':
                    return RedirectToAction("Edit");
                default:
                    return RedirectToAction("Index");
            }
        }
    }
}

HC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - My ASP.NET Application</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")

    </head>
    <body>
        <div class="container body-content">
            <nav class="navbar navbar-default" role="navigation">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
                    </div>
                    <div class="collapse navbar-collapse" id="navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="#">Link</a></li>
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="#">Action</a></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">Separated link</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">One more separated link</a></li>
                                </ul>
                            </li>
                        </ul>
                        @Html.Partial("_LoginPartial")
                    </div>
                </div>
            </nav>
        </div>
        @if (Session.Keys.Count > 0)
        {
            <div class="container body-content">
                <ul class="nav nav-tabs nav-justified">
                    @if (ViewContext.RouteData.Values["controller"].ToString() == "Pacientes")
                    {
                        <li class="tab-pane fade in active">@Html.ActionLink("Paciente", "Details", "Pacientes")</li>}
                    else
                    {
                        <li class="tab-pane">@Html.ActionLink("Paciente", "Details", "Pacientes")</li>}

                    @if (ViewContext.RouteData.Values["controller"].ToString() == "HistoriasClinicas")
                    {
                        <li class="tab-pane fade in active">@Html.ActionLink("Historia Clínica", "Details", "HistoriasClinicas")</li>}
                    else
                    {
                        <li class="tab-pane">@Html.ActionLink("Historia Clínica", "Details", "HistoriasClinicas")</li>}

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Estudios <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu" style="width: 100%; text-align: center">
                            <li>@Html.ActionLink("CCG", "Index", "CCGs")</li>
                            <li>@Html.ActionLink("ECO", "Index", "ECOs")</li>
                            <li>@Html.ActionLink("Laboratorios", "Index", "Laboratorios")</li>
                            <li>@Html.ActionLink("PEG", "Index", "PEGs")</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("Otros Estudios", "Index", "Estudios")</li>
                        </ul>
                    </li>

                    @if (ViewContext.RouteData.Values["controller"].ToString() == "Consultas")
                    {
                        <li class="tab-pane fade in active">@Html.ActionLink("Consultas", "Index", "Consultas")</li>}
                    else
                    {
                        <li class="tab-pane">@Html.ActionLink("Consultas", "Index", "Consultas")</li>}
                </ul>
            </div>
        }

        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
</html>

HC/Views/Shared/_SearchPacientePartial.cshtml
@model IEnumerable<HC.Models.Pacientes>

<div class="container body-content">
    <div class="table-responsive">
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Apellido)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TiposDocumentos.Descripcion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NumeroDocumento)
                </th>
                @*<th>
                        @Html.DisplayNameFor(model => model.Telefono)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Email)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Direccion)
                    </th>*@
                <th>
                    @Html.DisplayNameFor(model => model.FechaNacimiento)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ObrasSociales.Nombre)
                </th>
                <th></th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Apellido)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TiposDocumentos.Descripcion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NumeroDocumento)
                    </td>
                    @*<td>
                            @Html.DisplayFor(modelItem => item.Telefono)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Direccion)
                        </td>*@
                    <td>
                        @Html.DisplayFor(modelItem => item.FechaNacimiento)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ObrasSociales.Nombre)
                    </td>
                    <td>
                        <div class="btn-group btn-group-sm">
                            @Html.ActionLink("Detalle", "SetPacienteID", new { id = item.PacienteID, op = 'D' }, new { @class = "btn btn-info" })
                            @Html.ActionLink("Borrar", "SetPacienteID", new { id = item.PacienteID, op = 'B' }, new { @class = "btn btn-info" })
                        </div>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>